### ISSUE TITLE
Item Interface on Blood Altar Crash

### ISSUE THREAD

**Issue by gazpachoking** [CyclopsMC/IntegratedTunnels#1]
When I put an item interface onto a Blood Altar, from Blood Magic, I get the following crash:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  StepupfixCore (StepupFix-1.10.2-1.0.0.2.jar)
  LoadingPlugin (Quark-r1.0-60.jar)
  MovingWorldCoreMod (movingworld-1.10.2-0003-full.jar)
  StreamsCoreMod (Streams-1.9.4-0.2.1.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  FarseekCoreMod (Farseek-1.9.4-1.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  IvToolkit (IvToolkit-1.2.9.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.13.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 11/26/16 12:00 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at org.cyclops.integratedtunnels.core.part.PartTypeInterfacePositionedAddon.removeTargetFromNetwork(PartTypeInterfacePositionedAddon.java:69)
	at org.cyclops.integratedtunnels.core.part.PartTypeInterfacePositionedAddon.onBlockNeighborChange(PartTypeInterfacePositionedAddon.java:45)
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.onNeighborBlockChange(PartNetworkElement.java:145)
	at org.cyclops.integrateddynamics.core.helper.NetworkHelpers.onElementProviderBlockNeighborChange(NetworkHelpers.java:116)
	at org.cyclops.integrateddynamics.block.BlockCable.func_189540_a(BlockCable.java:284)
	at WayofTime.bloodmagic.altar.BloodAltar.update(BloodAltar.java:397)
	at WayofTime.bloodmagic.tile.TileAltar.func_73660_a(TileAltar.java:50)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.cyclops.integratedtunnels.core.part.PartTypeInterfacePositionedAddon.removeTargetFromNetwork(PartTypeInterfacePositionedAddon.java:69)
	at org.cyclops.integratedtunnels.core.part.PartTypeInterfacePositionedAddon.onBlockNeighborChange(PartTypeInterfacePositionedAddon.java:45)
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.onNeighborBlockChange(PartNetworkElement.java:145)
	at org.cyclops.integrateddynamics.core.helper.NetworkHelpers.onElementProviderBlockNeighborChange(NetworkHelpers.java:116)
	at org.cyclops.integrateddynamics.block.BlockCable.func_189540_a(BlockCable.java:284)
	at WayofTime.bloodmagic.altar.BloodAltar.update(BloodAltar.java:397)
	at WayofTime.bloodmagic.tile.TileAltar.func_73660_a(TileAltar.java:50)

-- Block entity being ticked --
Details:
	Name: BloodMagic:TileAltar // WayofTime.bloodmagic.tile.TileAltar
	Block type: ID #689 (tile.BloodMagic.altar // WayofTime.bloodmagic.block.BlockAltar)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-196,74,240), Chunk: (at 12,4,0 in -13,15; contains blocks -208,0,240 to -193,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #689 (tile.BloodMagic.altar // WayofTime.bloodmagic.block.BlockAltar)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: New World creative2
	All players: 1 total; [EntityPlayerMP['gazpachoking'/431, l='New World creative2', x=-195.70, y=74.00, z=237.81]]
	Chunk stats: ServerChunkCache: 841 Drop: 0
	Level seed: 6488507341660567137
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (-188,64,244), Chunk: (at 4,4,4 in -12,15; contains blocks -192,0,240 to -177,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1835 game time, 1835 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 23638 (now: false), thunder time: 127677 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 907666672 bytes (865 MB) / 4265082880 bytes (4067 MB) up to 5728894976 bytes (5463 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6146m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.2.2151 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2151.jar) 
	UCHIJAAAA	Forge{12.18.2.2151} [Minecraft Forge] (forge-1.10.2-12.18.2.2151.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	buildingbrickshooks{1.10.2-2.0.13} [Building Bricks Hooks] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.9} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	io.github.elytra.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJAAAA	immersiveengineering{0.10-50} [Immersive Engineering] (ImmersiveEngineering-0.10-50.jar) 
	UCHIJAAAA	JEI{3.13.4.384} [Just Enough Items] (jei_1.10.2-3.13.4.384.jar) 
	UCHIJAAAA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.1} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJAAAA	Quark{r1.0-60} [Quark] (Quark-r1.0-60.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.5} [Baubles] (Baubles-1.10.2-1.3.5.jar) 
	UCHIJAAAA	BetterAchievements{0.3.2.35} [Better Achievements] (BetterAchievements-1.10.2-0.3.2.35.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJAAAA	blockdrops{1.0.11} [Block Drops] (BlockDrops-1.10.2-1.0.11.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.1.0-66} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-66.jar) 
	UCHIJAAAA	infinitylib{1.10.2-0.2.1} [InfinityLib] (infinitylib-0.2.1.jar) 
	UCHIJAAAA	boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull] (boatifull-0.2.jar) 
	UCHIJAAAA	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCHIJAAAA	buildingbricks{1.10.2-2.0.13} [Building Bricks] (BuildingBricks-1.10.2-2.0.13.jar) 
	UCHIJAAAA	Chameleon{1.10-2.1.9} [Chameleon] (Chameleon-1.10-2.1.9.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJAAAA	cyclopscore{0.8.0} [Cyclops Core] (CyclopsCore-1.9.4-0.8.0.jar) 
	UCHIJAAAA	commoncapabilities{1.2.1} [CommonCapabilities] (CommonCapabilities-1.9.4-1.2.1.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.26} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.26.jar) 
	UCHIJAAAA	movingworld{1.10.2-0003} [Moving World] (movingworld-1.10.2-0003-full.jar) 
	UCHIJAAAA	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.10.2-0005-full.jar) 
	UCHIJAAAA	ding{1.0.1} [Ding] (Ding-1.10.2-1.0.1.jar) 
	UCHIJAAAA	Farseek{1.9.4} [Farseek] (Farseek-1.9.4-1.1.jar) 
	UCHIJAAAA	fw{1.3.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.3.0b.jar) 
	UCHIJAAAA	grapplemod{1.10.2-v8} [Grappling hook mod] (grapplemod-1.10-v8.jar) 
	UCHIJAAAA	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCHIJAAAA	integrateddynamics{0.6.3} [Integrated Dynamics] (IntegratedDynamics-1.10.2-0.6.3.jar) 
	UCHIJAAAA	integratedtunnels{1.0.0} [Integrated Tunnels] (IntegratedTunnels-1.10.2-1.0.0.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.0} [JourneyMap] (journeymap-1.10.2-5.3.0.jar) 
	UCHIJAAAA	jeresources{0.5.7.87} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.7.87.jar) 
	UCHIJAAAA	minecolonies{1.10.2-0.4.1796} [MineColonies] (minecolonies-universal-1.10.2-0.4.1796.jar) 
	UCHIJAAAA	mobends{0.22.5} [Mo'Bends] (mobends-0.22.5_for_MC-1.10.2.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.12} [Morpheus] (Morpheus-1.10.2-3.1.12.jar) 
	UCHIJAAAA	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	UCHIJAAAA	natura{1.10.2-4.0.0.93} [Natura] (natura-1.10.2-4.0.0.93.jar) 
	UCHIJAAAA	botanicaladdons{1.6} [Natural Pledge] (NaturalPledge-r1.6.jar) 
	UCHIJAAAA	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.10.2).jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	railcraft{10.0.0} [Railcraft] (Railcraft_1.10.2-10.0.0.jar) 
	UCHIJAAAA	reccomplex{1.2.4} [Recurrent Complex] (RecurrentComplex-1.2.4.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJAAAA	refinedrelocation{@VERSION@} [Refined Relocation] (RefinedRelocation-mc1.10.2-2.1.16.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.5.1} [Storage Drawers] (StorageDrawers-1.10.2-3.5.1.jar) 
	UCHIJAAAA	refinedstorage{1.2.5} [Refined Storage] (refinedstorage-1.2.5.jar) 
	UCHIJAAAA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJAAAA	roots{0.206} [Roots] (roots-0.206.jar) 
	UCHIJAAAA	AS_Ruins{16.2} [Ruins Spawning System] (Ruins-1.10.2.jar) 
	UCHIJAAAA	Signals{1.0} [Signals] (Signals-1.10.2-0.5.0-universal.jar) 
	UCHIJAAAA	SB{1.3} [Soundless Background] (SoundlessBackground-1.3.jar) 
	UCHIJAAAA	Streams{1.9.4} [Streams] (Streams-1.9.4-0.2.1.jar) 
	UCHIJAAAA	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	tombmanygraves{1.10.2-2.1.13} [Tomb Many Graves] (TombManyGraves-1.10.2-2.1.13.jar) 
	UCHIJAAAA	wtfcore{1.10.2_v1.1} [wtfcore] (WTF-Expedition_1.10.2_v1.1.jar) 
	Loaded coremods (and transformers): 
StepupfixCore (StepupFix-1.10.2-1.0.0.2.jar)
  
LoadingPlugin (Quark-r1.0-60.jar)
  vazkii.quark.base.asm.ClassTransformer
MovingWorldCoreMod (movingworld-1.10.2-0003-full.jar)
  
StreamsCoreMod (Streams-1.9.4-0.2.1.jar)
  streams.core.StreamsClassTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  
FarseekCoreMod (Farseek-1.9.4-1.1.jar)
  farseek.core.FarseekClassTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
IvToolkit (IvToolkit-1.2.9.jar)
  
LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.13.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['gazpachoking'/431, l='New World creative2', x=-195.70, y=74.00, z=237.81]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by gazpachoking** [comment]
Awesome, thanks!
