### ISSUE TITLE
Looking at a display panel crashes the game

### ISSUE THREAD

**Issue by Suiadan** [CyclopsMC/IntegratedTunnels#131]
#### Issue type:

- :bug: Bug

____

#### Short description:

When I look at a display panel, the entire screen goes sky blue for a while and then the game crashes. Disabling IntegratedTunnels prevents the crash.

If a world causes the crash, then loading the world again seems to crash again as well, also with the same stack trace.

Same as 
https://github.com/CyclopsMC/IntegratedDynamics/issues/627

#### Steps to reproduce the problem:

1. Place down some logic cable.

2. Place a display panel on the cable.

3. Crash.

#### Expected behaviour:

I don't expect to crash.
____

#### Versions:

- Integrated Dynamics: 0.11.16
- This mod: 1.5.6
- Minecraft: 1.12.2
- Forge: 14.23.4.2758

#### Log file:

https://pastebin.com/3vvq9KMj

Description: Rendering Block Entity
 
java.lang.ClassCastException: org.cyclops.integrateddynamics.part.PartTypePanelDisplay$State cannot be cast to org.cyclops.integrateddynamics.part.PartTypeConnectorOmniDirectional$State
    at org.cyclops.integrateddynamics.client.render.part.ConnectorOmniPartOverlayRenderer.renderPartOverlay(ConnectorOmniPartOverlayRenderer.java:49)
    at org.cyclops.integrateddynamics.client.render.tileentity.RenderCable.render(RenderCable.java:43)
    at org.cyclops.integrateddynamics.client.render.tileentity.RenderCable.render(RenderCable.java:35)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.render(TileEntityRendererDispatcher.java:155)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.render(TileEntityRendererDispatcher.java:130)
    at net.minecraft.client.renderer.RenderGlobal.redirect$tileEntityRender$zbn000(RenderGlobal.java:2651)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:705)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1347)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062)

**Comment by rubensworks** [comment]
No need to report duplicates, thanks in any case.
