### ISSUE TITLE
Crash loading existing save with new update

### ISSUE THREAD

**Issue by ItsTheKais** [CyclopsMC/IntegratedTunnels#142]
#### Issue type:

- :bug: Bug

____

#### Short description:

This occurred after updating the entire Integrated suite and then loading a save that had last been used with the immediately previous versions.

The save in question is my superflat creative test world, which as you would expect is absolutely plastered with all sorts of small builds, most of which I have little memory of, and I have no idea which of them might be a/the culprit here.

____

#### Versions:

Last used:
* Integrated Dynamics 0.11.18
* Integrated Tunnels 1.5.6
* Cyclops Core 0.11.11
* Common Capabilities 1.4.0
* Forge 14.23.5.2796
* Minecraft 1.12.2

Current:
* Integrated Dynamics 1.0.0
* Integrated Tunnels 1.0.0
* Integrated Crafting 1.0.0
* Integrated Terminals 1.0.0
* Cyclops Core 1.0.0
* Common Capabilities 2.0.0
* Forge 14.23.5.2796
* Minecraft 1.12.2

#### Log file:

https://pastebin.com/R3n7gQTZ

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by GreyMario** [comment]
Culprit confirmed to be _any_ predicate used for importing or exporting. Even a simple `Item Stackable` predicate will cause this crash.

Versions:
- Minecraft: `1.12.2`
- Forge: `14.23.5.2768`
- InDynamics: `1.0.0`
- InTunnels: `1.6.0`
- InCrafting: `1.0.0`
- InTerminals: `1.0.0`
- CyclopsCore: `1.0.0`
- CommonCapabilities: `2.0.0`

Stack trace:
```
java.lang.NullPointerException: Exception in server tick loop
	at org.cyclops.integratedtunnels.core.predicate.IngredientPredicate.hashCode(IngredientPredicate.java:97)
	at org.cyclops.integratedtunnels.core.predicate.IngredientPredicateItemStackOperator.hashCode(IngredientPredicateItemStackOperator.java:62)
	at org.cyclops.integratedtunnels.part.aspect.TunnelConnectionPositionedNetwork.hashCode(TunnelConnectionPositionedNetwork.java:36)
	at org.cyclops.integratedtunnels.part.aspect.TunnelConnectionPositionedNetworkCapabilityProvider.hashCode(TunnelConnectionPositionedNetworkCapabilityProvider.java:37)
	at com.google.common.base.Equivalence$Equals.doHash(Equivalence.java:351)
	at com.google.common.base.Equivalence.hash(Equivalence.java:117)
	at com.google.common.cache.LocalCache.hash(LocalCache.java:1851)
	at com.google.common.cache.LocalCache.getIfPresent(LocalCache.java:4134)
	at com.google.common.cache.LocalCache$LocalManualCache.getIfPresent(LocalCache.java:5054)
	at org.cyclops.integratedtunnels.core.TunnelHelpers.moveSingleStateOptimized(TunnelHelpers.java:92)
	at org.cyclops.integratedtunnels.part.aspect.TunnelAspectWriteBuilders$Item.lambda$static$13(TunnelAspectWriteBuilders.java:568)
	at org.cyclops.integrateddynamics.core.part.aspect.build.AspectBuilder$BuiltWriter.write(AspectBuilder.java:428)
	at org.cyclops.integrateddynamics.part.aspect.write.AspectWriteBase.update(AspectWriteBase.java:57)
	at org.cyclops.integrateddynamics.core.part.aspect.build.AspectBuilder$BuiltWriter.update(AspectBuilder.java:451)
	at org.cyclops.integrateddynamics.core.part.write.PartTypeWriteBase.update(PartTypeWriteBase.java:96)
	at org.cyclops.integrateddynamics.core.part.write.PartTypeWriteBase.update(PartTypeWriteBase.java:48)
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:134)
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:408)
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_55_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by rubensworks** [comment]
Thanks for the additional information @GreyMario!.
